version: "3.9"
services:
  db:
    image: postgres:14-alpine
    restart: always
    container_name: ex8_db
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data/
    networks:
      - ecommerce_network
    ports:
      - "5432:5432"

  api:
    build: .
    restart: always
    container_name: ex8_api
    environment:
      DB_SOURCE: postgres://postgres:postgres@db:5432/ecommerce?sslmode=disable
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - ecommerce_network
    depends_on:
      - db
#    entrypoint:
#      [
#        "/app/wait-for-it.sh",
#        "db:5432",
#        "--",
#        "/app/start.sh"
#      ]
    command: [ "/app/server" ]

volumes:
  db_data:

networks:
  ecommerce_network: