version: "3.9"
services:
  db:
    image: postgres:14-alpine
    restart: always
    container_name: ex7_db
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data/
    networks:
      - ecommerce_network
    ports:
      - "5432:5432"

volumes:
  db_data:

networks:
  ecommerce_network: